# Generated by Django 4.2.16 on 2024-09-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('description_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemIndependentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_indp_claims', to='api.patent')),
            ],
        ),
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.TextField()),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_system_components', to='api.patent')),
            ],
        ),
        migrations.CreateModel(
            name='IndependentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indp_claims', to='api.patent')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_link', models.URLField()),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.patent')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='api.patent')),
            ],
        ),
    ]
