# Generated by Django 4.2.16 on 2024-09-25 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='patent',
        ),
        migrations.RemoveField(
            model_name='independentclaim',
            name='patent',
        ),
        migrations.RemoveField(
            model_name='systemcomponent',
            name='patent',
        ),
        migrations.RemoveField(
            model_name='systemindependentclaim',
            name='patent',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='IndependentClaim',
        ),
        migrations.DeleteModel(
            name='Patent',
        ),
        migrations.DeleteModel(
            name='SystemComponent',
        ),
        migrations.DeleteModel(
            name='SystemIndependentClaim',
        ),
    ]
